apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: addon-manager-operator
spec:
  selector:
    matchLabels:
      name: addon-manager-operator
  template:
    metadata:
      labels:
        name: addon-manager-operator
    spec:
      serviceAccountName: addon-manager-operator
      tolerations:
      - operator: Exists
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: addon-manager-operator
          # Replace this with the built image name
          image: docker.io/jiuchen1986/addon-manager-operator:v0.0.1
          command:
          - addon-manager-operator
          args:
          - --instance-id
          - "$(POD_NAME)"
          - --addons-dir
          - /addons
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              # valueFrom:
                # fieldRef:
                  # fieldPath: metadata.namespace
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "addon-manager-operator"
          volumeMounts:
          - name: addons
            mountPath: /addons
      volumes:
      - name: addons
        hostPath:
          path: /etc/kubernetes/addons
          type: DirectoryOrCreate
      securityContext:
        runAsUser: 0
